### ISSUE TITLE
docker logs -f dhcpd shows error message

### ISSUE THREAD

**Issue by Empor-co** [prehley/rpi-dhcpd#1]
Hi,

when I try to run the service within the container I get the following error message:
```
chown: invalid user: ‘dhcpd:dhcpd’
chown: invalid user: ‘dhcpd:dhcpd’
```

which likely comes from the` chown dhcpd:dhcpd `for the lease files.

Best regards,

Empor

**Comment by Empor-co** [comment]
Just added `useradd -ms /bin/bash dhcpd` at the end of the RUN section:
`
[...]
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -ms /bin/bash dhcpd`

**Comment by Cossey** [comment]
Thanks for this bit of info; hopefully he will update the Readme or the Docker script to fix this error.

**Comment by prehley** [comment]
Patch applied with the fix.  Thanks.
